"""
Report data models.

PipelineAsset  ??a single drug / therapy pipeline entry.
RNPVResult     ??risk-adjusted NPV calculation output.
Section        ??one named section of a report (title + body markdown).
Report         ??top-level report returned by any sector agent.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

MISSING_DATA_PLACEHOLDER = "[?곗씠??誘명솗??"


@dataclass
class PipelineAsset:
    """Single pipeline programme for a BIO/healthcare company.

    Any field that could not be extracted from source data must be set to
    ``MISSING_DATA_PLACEHOLDER`` rather than left blank or guessed.
    """

    pipeline_name: str  # ?뚯씠?꾨씪?몃챸
    indication: str  # ?곸쓳利?    clinical_stage: str  # ?꾩긽?④퀎  e.g. "Ph1", "Ph2", "Ph3", "NDA", "Approved"
    expected_loa: str  # ?덉긽 LoA  (Likelihood of Approval, e.g. "45%" or MISSING)
    rnpv_contribution: str  # rNPV 湲곗뿬  (e.g. "$120M" or MISSING)

    def to_table_row(self) -> str:
        """Return a Markdown table row for this asset."""
        return (
            f"| {self.pipeline_name} "
            f"| {self.indication} "
            f"| {self.clinical_stage} "
            f"| {self.expected_loa} "
            f"| {self.rnpv_contribution} |"
        )


@dataclass
class RNPVResult:
    """Output of a rough rNPV calculation.

    Formula applied::

        rNPV = 誇_i  (peak_sales_i 횞 loa_i 횞 royalty_rate 횞 duration_factor_i)
                    / (1 + discount_rate) ^ years_to_launch_i

    where ``peak_sales_i`` and ``years_to_launch_i`` come from the supplied
    financial projections and ``loa_i`` is the per-asset probability of approval.
    """

    total_rnpv_usd_million: Optional[float]
    per_asset: dict[str, Optional[float]] = field(default_factory=dict)
    discount_rate: float = 0.10
    notes: str = ""
    data_complete: bool = True

    @property
    def summary_line(self) -> str:
        if self.total_rnpv_usd_million is None:
            return f"Total rNPV: {MISSING_DATA_PLACEHOLDER}"
        return (
            f"Total rNPV ??${self.total_rnpv_usd_million:,.1f}M "
            f"(discount rate: {self.discount_rate:.0%})"
        )


@dataclass
class Section:
    title: str
    body: str  # Markdown-formatted content

    def to_markdown(self) -> str:
        return f"## {self.title}\n\n{self.body}\n"


@dataclass
class Report:
    """Top-level report produced by a sector agent."""

    company_name: str
    sector: str
    agent_name: str
    sections: list[Section] = field(default_factory=list)
    pipeline_assets: list[PipelineAsset] = field(default_factory=list)
    rnpv: Optional[RNPVResult] = None
    warnings: list[str] = field(default_factory=list)

    # ------------------------------------------------------------------
    # Pipeline table helpers
    # ------------------------------------------------------------------

    PIPELINE_TABLE_HEADER = (
        "| ?뚯씠?꾨씪?몃챸 | ?곸쓳利?| ?꾩긽?④퀎 | ?덉긽 LoA | rNPV 湲곗뿬 |\n"
        "|---|---|---|---|---|"
    )

    def pipeline_table_markdown(self) -> str:
        """Render the pipeline assets as a Markdown table."""
        if not self.pipeline_assets:
            return f"*?뚯씠?꾨씪???곗씠???놁쓬 ??{MISSING_DATA_PLACEHOLDER}*"
        rows = [asset.to_table_row() for asset in self.pipeline_assets]
        return self.PIPELINE_TABLE_HEADER + "\n" + "\n".join(rows)

    # ------------------------------------------------------------------
    # Full report rendering
    # ------------------------------------------------------------------

    def to_markdown(self) -> str:
        lines: list[str] = [f"# {self.company_name} ??{self.sector.upper()} Report\n"]
        lines.append(f"*Generated by: {self.agent_name}*\n")

        for section in self.sections:
            lines.append(section.to_markdown())

        if self.pipeline_assets:
            lines.append("## ?뚯씠?꾨씪???붿빟\n")
            lines.append(self.pipeline_table_markdown())
            lines.append("")

        if self.rnpv is not None:
            lines.append("## rNPV 異붿젙\n")
            lines.append(self.rnpv.summary_line)
            if self.rnpv.notes:
                lines.append(f"\n> {self.rnpv.notes}")
            lines.append("")

        if self.warnings:
            lines.append("---\n")
            lines.append("**寃쎄퀬 / 二쇱쓽?ы빆**\n")
            for w in self.warnings:
                lines.append(f"- {w}")

        return "\n".join(lines)
