// Development only. Never imports a production env file or resets an existing DB.
import { existsSync, openSync, closeSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { runNpm } from "../tools/local-development.mjs";
import { fileURLToPath } from "node:url";

process.chdir(fileURLToPath(new URL("../", import.meta.url)));
if (process.env.DATABASE_URL && process.env.DATABASE_URL !== "file:./dev.db") {
  throw new Error("Remove the external DATABASE_URL from this development environment before setup.");
}
const marker = "# Generated by Dealmind Codespaces fixture setup";
const existing = existsSync(".env.local") ? readFileSync(".env.local", "utf8") : null;
if (existsSync(".env") || (existing && (!existing.startsWith(marker + "\n") || !existing.includes('DATABASE_URL="file:./dev.db"')))) {
  throw new Error("Existing env file preserved. Review it before manually running the local setup scripts.");
}
const publicUrl = process.env.CODESPACE_NAME && process.env.GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN
  ? `https://${process.env.CODESPACE_NAME}-3000.${process.env.GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}`
  : "http://localhost:3000";
if (!existing) writeFileSync(".env.local", [
  marker,
  'DATABASE_URL="file:./dev.db"',
  `NEXTAUTH_URL="${publicUrl}"`,
  'NEXTAUTH_URL_INTERNAL="http://127.0.0.1:3000"',
  `NEXTAUTH_SECRET="${randomBytes(32).toString("hex")}"`,
  'STORAGE_MODE="local"',
  "",
].join("\n"), { flag: "wx", mode: 0o600 });

const env = { ...process.env, DATABASE_URL: "file:./dev.db" };
function run(args) {
  runNpm(args, env);
}
if (process.argv.includes("--skip-install")) {
  if (!existsSync("node_modules/prisma/build/index.js") || !existsSync("node_modules/tsx/dist/cli.mjs")) {
    throw new Error("Install dependencies with npm ci --ignore-scripts before --skip-install.");
  }
} else {
  run(["ci", "--ignore-scripts", "--no-audit", "--no-fund"]);
}
if (!existsSync("prisma/dev.db") || statSync("prisma/dev.db").size === 0) {
  if (!existsSync("prisma/dev.db")) closeSync(openSync("prisma/dev.db", "wx"));
  run(["exec", "--", "prisma", "generate", "--schema", "prisma/schema.sqlite.prisma"]);
  run(["exec", "--", "prisma", "db", "push", "--schema", "prisma/schema.sqlite.prisma"]);
  run(["exec", "--", "tsx", "prisma/seed.ts"]);
} else {
  // Rebuilds must not overwrite work already saved in the Codespace.
  run(["exec", "--", "prisma", "generate", "--schema", "prisma/schema.sqlite.prisma"]);
}
run(["run", "setup:fonts"]);
run(["exec", "--", "tsx", "tools/test-vc-design-review.ts", "seed"]);
run(["exec", "--", "tsx", "tools/test-home-pe-design.ts", "seed"]);
console.log("Ready: npm run dev:local -- --hostname 0.0.0.0");
console.log("Keep forwarded port 3000 PRIVATE. Use the same Codespace from both computers.");
